sudo: required
services:
  - docker

before_install:
  - docker build -t docker-react -f Dockerfile.dev .

script:
  - docker run -v /app/node_modules -v $(pwd):/app  docker-react npm run test -- --coverage
